{% set name = "conda-workon" %}
{% set version = "0.4.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "0f94909c703f2fa39c1f4830808205ba8f1303960bfb85687bd5fb7cc0580e1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - conda-workon = conda_workon:main_workon
    - conda-worktmp = conda_workon:main_tmp

  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - conda <4.4

  run:
    - python >={{ python_min }}
    - conda <4.4
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  commands:
    - conda workon --help
    - conda-workon --help
    - conda worktmp --help
    - conda-worktmp --help

about:
  home: https://bitbucket.org/flub/conda-workon
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Activate conda environments in subshells'

extra:
  recipe-maintainers:
    - pmlandwehr
    - flub
