travis:
  secure:
    BINSTAR_TOKEN: rDNfbUuFcG0vUQyHvhomlJkXu9DymhVy5XCdIh7dQx+awMkmraGLTEx4BSTorPFF5X0la0tDS07g2VWihVk3rNbPHDsh9eL4AQJ5kREt8W4YnGEBurnFvGJo9p3NOEK46rvRd1G26xZfDZrDm6/KHBDVCCi3vjudzWfIak8xB9er94MsRwanKZAfTqECs+7YpKGxzeSD/ytcPh/bAnavxNYeQtO6DYUvihnByYR4DjAYKjbfFRyDCTdCw1fB0uvCyaWzRVhv+S5ZkXpz7uAwZnbVVIKulgHJsadChfFVLxdsyBktrMyGwOCpBiy8MiNXNX6DC6ZavhPWUolZCU9uB5SYAFFmbZmgQZXVFpJQD3YCODzw0+R5WivcAhirbutMLb+N/RmuX8usXwMr4a6lo2TktvNUvh4fuKpQKuz8x4Cicc1E6cSFOgQGWHFQwz5mP8dneinrlAgM2cYChp+iyEMICJUTB5VmJgEMEYyA70mysLZ9fEUbv+bJ/b1HR2YU3Z4zlPJe9L83Hg2xTa/4ix+WB+IsR2WKYLX3o99U0d5D6ProwylCcfVpudw9Ob0LvXPCEGvC49c1eH9G6gxZ18cXupUhWsJoHy/nq1GGM9WWSwFIi7ljNQC6oDBiEKY8lPPovt7Fb5Q2qdLk4kYJoHVEM+uIe7TcUTdIFm7BgEk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
