travis:
  secure:
    BINSTAR_TOKEN: ASMjh4tz2+Esz1dbNQ4Wyw26CvDIme2FT3oOo42CPwVgny5hpsgAnh3OiH+mzVQxnE0JGI2U7wYxOH527i8ejTEZAQ2VwCLMw+9ogu7HvBjjCckESwDDUxGZjc5ZacARm7TtudhElLuZDx0SfX+wl9RlczdkWdU3G0XxmWjdTdHAikTGclCOI4i7GRJz8ki87bLh/vI7yMIRdwbPQSviQKJUHxNDvDva11EBs/Lkq8udEVbDqGYXDiP1U8nqmjfTmK7gakVZHFF4mnoJ6rS/gM//ngQENZz09NfNyjye8ndd66uYbZIap89Z1ZUlnE7oIN3+Ns212frSdCZwmQQxXlJvGyFeR92vG17tXRH7ukZTfedaSxPxFdPkrQik5DisCOuWpAhMZXW4XmjzkQ9dTF9teKMy5T87kEoQ7l+rYdk/gKkJrvSE/riwQ/hlR1YsMLrZ+ADEgeuctExf/QPQAFpFI8YLny7ndbOBg9fW5v3kEX80gkZOSJ3sQ3B1Sx7VaDB5SkiQPsx9Lnnhux5laE/YxS+uIWwrOBpjo85cvXjdC+gfKE4p6OATBn4jYglu38w3kKLeHP/BXGmPJcbRE95XuCkKTELEgwQv8b4LMFuFe1xwEM9qDKJiN0WW1XmPwpX8KP3fPDy5wvqGkssKNErL1g//auk5dSZolvFRtb8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
